version: '3.8'

services:
  shareit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: shareit-prod
    environment:
      - NODE_ENV=production
    ports:
      - "${PORT:-4847}:${PORT:-4847}"
    restart: unless-stopped
    command: >
      sh -c "
        /usr/local/bin/port-detector.sh &&
        source .env &&
        serve -s web-build -l ${PORT:-4847}
      "
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-4847}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: shareit-network